name: flutter_ci_cd_demo
description: Dart Code Metrics helper for aggregated report generation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0 <4.0.0"

dev_dependencies:
  melos: ^4.1.0
  lint: ^2.2.0
  